version: "3.4"

services:
  github-workflow-dispatch:
    image: samuelrunggaldier/github-workflow-dispatch:latest
    restart: always
    secrets:
      - GITHUB_WORKFLOW_DISPATCH_APIKEY
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 60s
        monitor: 60s
      labels:
        - traefik.enable=true
        - traefik.http.services.github-workflow-dispatch.loadbalancer.server.port=3000
        - traefik.http.routers.github-workflow-dispatch.tls=true
        - traefik.http.routers.github-workflow-dispatch.tls.certresolver=myresolver
        - traefik.http.routers.github-workflow-dispatch.rule=Host(`workflow-dispatch.mycooldomain.com`)
        - traefik.http.routers.github-workflow-dispatch.service=github-workflow-dispatch
        - traefik.http.routers.github-workflow-dispatch.entrypoints=websecure
        - traefik.docker.network=traefik

secrets:
  GITHUB_WORKFLOW_DISPATCH_APIKEY:
    external: true

networks:
  traefik:
    external: true